list(APPEND SOURCES DayTime/DayTime.c)
list(APPEND SOURCES Det/Det.c)
list(APPEND SOURCES MotorCtrl/MotorCtrl.c)
list(APPEND SOURCES ntp/ntp.c)
list(APPEND SOURCES shButton/shButton.c)
list(APPEND SOURCES shCom/shCom.c)
list(APPEND SOURCES shDiscovery/shDiscovery.c)
list(APPEND SOURCES shScheduler/shScheduler.c)
list(APPEND SOURCES shStateMachine/shStateMachine.c)
list(APPEND SOURCES sunMoon/sunMoon.c)
list(APPEND SOURCES update/update.c)
list(APPEND SOURCES wifihdl/WifiHdl.c)
list(APPEND SOURCES main.c)

idf_component_register(SRCS ${SOURCES}
                    INCLUDE_DIRS "include" "wifihdl" "update" "ntp" "shDiscovery" "shCom" "shStateMachine" "MotorCtrl" "Det" "shScheduler" "sunmoon" "DayTime" "shButton")